### ISSUE TITLE
onBeforeInput event

### ISSUE THREAD

**Issue by MonaMayrhofer** [purescript-halogen/purescript-dom-indexed#31]
There does not seem to be any mention of the [beforeinput](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforeinput_event) event within this package.

Is there a reason for this?

And if no, where would that event find it's place? From a quick look over this package it seems like `GlobalEvents` would be a good candidate - because then it's colocated with `onInput`, however i am not sure of all the implications of putting it there...

https://github.com/purescript-halogen/purescript-dom-indexed/blob/b462b7391f89cda71d8559cc6f0a49755fae6a99/src/DOM/HTML/Indexed.purs#L48-L53

Thanks a lot!

**Comment by garyb** [comment]
I think it makes sense add it there - some of the organization of these may not be 100% accurate, but it's kinda harmless with events since they just won't be triggered. I think `onInput` is here because it can apply to any element thanks to `contenteditable`, so the same logic would apply to `onBeforeInput`.
